name: amber-rekognition-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pytest
  - ipython
  - jupyterlab
  - matplotlib
  - plotly
  - ipyleaflet
  - pylint
  - autopep8
  - lxml
  - boto3
  - awswrangler
  - PyPDF2
  - json
  - requests
  - pip
  - pip:
    - pytest-cov
    - requests

# Variables de entorno para el entorno de desarrollo
variables:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  AWS_DEFAULT_REGION: "us-east-1"
  BUCKET_NAME: "itam-proyecto-saraluz"
  BUCKET_NAME_TEST: "itam-proyecto-saraluz-test"
