name: proyecto_arquitectura
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pytest
  - ipython
  - jupyterlab
  - matplotlib
  - plotly
  - ipyleaflet
  - pylint
  - autopep8
  - lxml
  - boto3
  - awswrangler
  - PyPDF2
  - json
  - requests
